config/routes.rb
Rails.application.routes.draw do

  resources :prospects

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users

  devise_scope :user do
    get "/admin/sign-in" => 'devise/sessions#new'
    get "/admin/sign-up" => 'devise/registrations#new'
  end
  
  get 'about', to: 'pages#about'
  get 'faq', to: 'pages#faq'
  get 'bio', to: 'pages#bio'
  get 'basic-divorce', to: 'pages#basic'
  get 'divorce-with-property', to: 'pages#property'
  get 'divorce-with-children', to: 'pages#children'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/questions'
  get 'dashboard/prospects'
  get 'dashboard/posts'
  get 'dashboard/posts/new', to: 'dashboard#newpost'
  get 'dashboard/posts/:id/edit', to: 'dashboard#editpost', as: "edit_post"
  get 'dashboard/questions/new', to: 'dashboard#newquestion'
  get 'dashboard/questions/:id/edit', to: 'dashboard#editquestion', as: "edit_question"
  get 'pages/download_pdf'
  get 'pages/download_parenting_class_pdf'
  get 'pages/download_intermediary_pdf'

  get 'posts/tags/:tag', to: 'posts#index', as: "tag"

  resources :questions
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end
  resources :contacts

  root to: 'pages#home'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!
  before_action do
    redirect_to root_path unless current_user && current_user.admin?
  end

  def index
  	@posts = Post.order('pub_date desc').limit(4)
    @questions = Question.order('created_at desc').limit(4)
    @prospects = Prospect.order('created_at desc').limit(5)
  end

  def questions
    @questions = Question.order('created_at desc').page(params[:page]).per(10)
  end

  def posts
  	@posts = Post.order('pub_date desc').page(params[:page]).per(10)
  end

  def newpost
    @posts = Post.all
  end

  def editpost
    @post = Post.friendly.find(params[:id])
  end

  def newquestion
  end

  def editquestion
    @question = Question.find(params[:id])
  end

  def prospects
    @prospects = Prospect.order('created_at desc').page(params[:page]).per(15)
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_dashboardEditPost.html.erb
<div class="container-fluid">
	<div class="dashboard-box-top">
	<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight sky-blue">Edit Post</h2>
		</div>
	</div>
	<div class="row">
		<%= form_for @post do |f| %>
		<div class="col-md-8">
			<div class="form-group">
				<%= f.text_field :title, class: "form-control-post-title", placeholder: "Post Title", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.text_area :body, class: "form-control redactor" %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-group">
				<label>Author</label>
				<%= f.text_field :author, class: "form-control", value: "Connie Chadwick" %>
			</div>
			<div class="form-group">
				<label>Tags</label>
				<%= f.text_field :all_tags, class: "form-control", placeholder: "Tags separated by a comma" %>
			</div>
			<div class="form-group" id="date_picker">
				<label>Publication Date</label>
				<%= f.text_field :pub_date, class: "form-control", placeholder: "Publication Date" %>
			</div>
			<div class="form-group">
				<% if @post.status == "published" %>
					<p class="latobold main-text">Current Status: <span class="sky-blue"><%= @post.status.capitalize %></span></p>
					<%= f.submit "Update Post", class: "btn btn-navy", name: "publish" %>
					<%= f.submit "Unpublish", class: "btn btn-default", name: "draft" %>
				<% elsif @post.status == "draft" %>
					<p class="latobold main-text">Current Status: <span class="light-gray"><%= @post.status.capitalize %></span></p>
					<%= f.submit "Publish Now", class: "btn btn-navy", name: "publish" %>
					<%= f.submit "Update Draft", class: "btn btn-default", name: "draft" %>
				<% end %>
			</div>

			
			
			
  
  <div class="tag_cloud">
  	<h3 class="latobold">Used tags:</h3>
    <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
      <p class="tag-box"><%= tag.name %></p>
    <% end %>
  </div>
		</div>

		<% end %>

		
	</div>
</div>
</div>

app/views/dashboard/_dashboardEditQuestion.html.erb
<div class="container-fluid">
	<div class="dashboard-box-top">
	<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight sky-blue">Edit Question</h2>
		</div>
	</div>
	<div class="row">
		<%= form_for @question do |f| %>
		<div class="col-md-12">
			<div class="form-group">
				<%= f.text_field :name, class: "form-control-post-title", placeholder: "Question", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.text_area :answer, class: "form-control redactor", placeholder: "Add answer..." %>
			</div>
			<% if @question.status == "published" %>
					<p class="latobold main-text">Current Status: <span class="sky-blue"><%= @question.status.capitalize %></span></p>
					<%= f.submit "Update Post", class: "btn btn-navy", name: "publish" %>
					<%= f.submit "Unpublish", class: "btn btn-default", name: "draft" %>
				<% elsif @question.status == "draft" %>
					<p class="latobold main-text">Current Status: <span class="light-gray"><%= @question.status.capitalize %></span></p>
					<%= f.submit "Publish Now", class: "btn btn-navy", name: "publish" %>
					<%= f.submit "Update Draft", class: "btn btn-default", name: "draft" %>
				<% end %>
		
	
		</div>
		<% end %>
	</div>
</div>
</div>

app/views/dashboard/_dashboardMain.html.erb
<div class="container-fluid">
	<!--<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight navy">Welcome back, <span class="navy">Aaron&nbsp;Johnson</span></h2>
		</div>
	</div>-->
	<div class="row">
		<div class="col-md-6">
			<div class="dashboard-box">
				<h2 class="latolight dash-header sky-blue">Recent Posts<a href="/dashboard/posts/new"><span class="btn btn-navy pull-right"><span class="glyphicon glyphicon-plus" aria-	hidden="true"></span></span></a></h2>
				<div class="table-responsive">
					<table class="table table-hover">
						<tr>
							<th class="latobold">Post Title</th>
							<th class="latobold">Publication Date</th>
							<th class="latobold">Status</th>
							<th class="latobold"></th>
						</tr>
						<% for post in @posts %>
							<tr>
								<td class="latoregular"><%= post.title %></td>
								<td class="latoregular"><%= post.pub_date.strftime('%B %-d, %Y') %></td>
								<% if post.status === "published" %>
								<td class="latobold sky-blue"><%= post.status.capitalize %></td>
								<% elsif post.status === "draft" %>
								<td class="latoregular gray"><%= post.status.capitalize %></td>
								<% end %>
								<td class="latoregular"><span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"	></span></td>
							</tr>
						<% end %>
					</table>
					<p class="latobold view-all"><%= link_to "View all Posts", dashboard_posts_path, class: "btn btn-navy" %>
				</div>	
			</div>
		</div>
		<div class="col-md-6">
			<div class="dashboard-box">
				<h2 class="latolight dash-header sky-blue"> Recent FAQ<a href="/dashboard/questions/new"><span class="btn btn-navy pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></span></a></h2>
				<div class="table-responsive">
					<table class="table table-hover">
						<tr>
							<th class="latobold">Question</th>
							<th class="latobold">Status</th>
							<th></th>
						</tr>
						<% for question in @questions %>
						<tr>
							<td class="latoregular"><%= question.name %></td>
							<% if question.status === "published" %>
								<td class="latobold sky-blue"><%= question.status.capitalize %></td>
								<% elsif question.status === "draft" %>
								<td class="latoregular gray"><%= question.status.capitalize %></td>
								<% end %>
							<td><span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"	></span></td>
						</tr>
						<% end %>
					</table>
					<p class="latobold view-all"><%= link_to "View all Questions", dashboard_questions_path, class: "btn btn-navy" %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="dashboard-box">
				<h2 class="latolight dash-header sky-blue">Recent Prospects</h2>
				<div class="table-responsive">
					<table class="table table-hover">
						<tr>
							<th class="latobold">Name</th>
							<th class="latobold">Email</th>
							<th class="latobold">Phone</th>
							<th class="latobold">Type</th>
							<th></th>
						</tr>
						<% for prospect in @prospects %>
						<tr>
							<td class="latoregular"><%= prospect.full_name %></td>
							<td class="latoregular"><%= prospect.email %></td>
							<td class="latoregular"><%= prospect.phone %></td>
							<td class="latoregular"><%= prospect.option %></td>
							<td class="latoregular"><span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"	></span></td>
						</tr>
						<% end %>
					</table>
					<p class="latobold view-all"><%= link_to "View all Prospects", dashboard_prospects_path, class: "btn btn-navy" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/dashboard/_dashboardNav.html.erb
<div class="dashnav-container">
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand latolight" href="/dashboard">Admin Console</a>
	    </div>
	    <div id="navbar" class="navbar-collapse collapse">
	    	<ul class="nav navbar-nav">
	    		<li><a href="/">Main Site</a></li>
	    	</ul>
	      <ul class="nav navbar-nav navbar-right">
	        <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'index' %>"><a href="/dashboard">Dashboard</a></li>
					<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'posts' %>"><a href="/dashboard/posts">Posts</a></li>
					<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'questions' %>"><a href="/dashboard/questions">FAQ</a></li>
					<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'prospects' %>"><a href="/dashboard/prospects">Prospects</a></li>
	        <li><%= link_to "Logout", destroy_user_session_path, class: "latolight", method: :delete %> </li>
	      </ul>
	      <!--<form class="navbar-form navbar-right">
	        <input type="text" class="form-control" placeholder="Search...">
	      </form>-->
	    </div>
	  </div>
	</nav>
</div>

app/views/dashboard/_dashboardNewQuestion.html.erb
<div class="container-fluid">
	<div class="dashboard-box-top">
	<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight sky-blue">New Question</h2>
		</div>
	</div>
	<div class="row">
		<%= form_for Question.new do |f| %>
		<div class="col-md-12">
			<div class="form-group">
				<%= f.text_field :name, class: "form-control-post-title", placeholder: "Question", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.text_area :answer, class: "form-control redactor", placeholder: "Add answer...", required: "required" %>
			</div>
		
			<%= f.submit "Publish Now", class: "btn btn-navy", name: "publish" %>
			<%= f.submit "Save as Draft", class: "btn btn-default", name: "draft" %>
		</div>
		<% end %>
	</div>
</div>
</div>

app/views/dashboard/_dashboardPosts.html.erb
<div class="container-fluid">

<div class="dashboard-box-top">

	<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight sky-blue">Posts<a href="/dashboard/posts/new"><span class="btn btn-navy pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></span></a></h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			
				<div class="table-responsive">
					<table class="table table-hover">
						<tr>
							<th class="latobold main-text">Post Title</th>
							<th class="latobold main-text">Publication Date</th>
							<th class="latobold main-text">Status</th>
							<th class="latobold main-text"></th>
						</tr>
						<% for post in @posts %>
							<tr>
								<td class="latoregular"><%= link_to post.title, edit_post_path(post) %></td>
								<td class="latoregular"><%= post.pub_date.strftime('%B %-d, %Y') %>	</td>
								<% if post.status === "published" %>
								<td class="latobold sky-blue"><%= post.status.capitalize %></td>
								<% elsif post.status === "draft" %>
								<td class="latoregular gray"><%= post.status.capitalize %></td>
								<% end %>
								<td>
									<%= link_to post, method: :delete, data: {confirm: "Are you sure?" } do %>
										<span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"></span>
									<% end %>
								</td>
							</tr>
						<% end %>

					</table>
					<%= paginate @posts, :theme => 'twitter-bootstrap-3' %>
				</div>

		</div>
	</div>

</div>
</div>

app/views/dashboard/_dashboardProspects.html.erb
<div class="container-fluid">
	<div class="dashboard-box-top">
	<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight sky-blue">Prospects</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<p class="latolight">Click on name to view full details</p>
		<div class="table-responsive">
			<table class="table table-hover">
				<tr>
					<th class="latobold main-text">Name</th>
					<th class="latobold main-text">Received</th>
					<th class="latobold main-text">Type</th>
					<th class="latobold main-text">Conflict Status</th>
					<th class="latobold main-text"></th>
				</tr>
				<% for prospect in @prospects %>
					<tr>
						<td class="latoregular sky-blue"><%= link_to prospect.full_name, "", data: {toggle: "modal", target: "#prospectModal-#{prospect.id}"} %></td>
						<td class="latoregular"><%= prospect.created_at.strftime('%B %-d, %Y') %>	</td>
						<td class="latoregular"><%= prospect.option %></td>
						<td class="latoregular"><a href="#" id="status" data-type="select" data-resource="prospect" data-name="status" data-url="/prospects/<%= prospect.id %>" data-original-title="Edit status"><%= prospect.status %></a></td>




						<td>
									<%= link_to prospect, method: :delete, data: {confirm: "Are you sure?" } do %>
										<span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"></span>
									<% end %>
								</td>
					</tr>




<!-- Modal -->
<div class="modal fade" id="prospectModal-<%= prospect.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel"><%= prospect.option %></h4>
      </div>
      <div class="modal-body">

      	<p class="latoblack large-text"><%= prospect.full_name %></p>
      	<p class="latolight main-text"><span class="latobold">Email: </span><%= prospect.email %></p>
      	<p class="latolight main-text"><span class="latobold">Phone: </span><%= prospect.phone %></p>
      	<p class="latolight main-text"><span class="latobold">Address: </span><br>
      		<%= prospect.street %><br>
      		<%= "#{prospect.city}" + ", " + "#{prospect.state}" + " #{prospect.zip} " %></p>

      	<p class="latolight main-text"><span class="latobold">Resided there how long?: </span><%= prospect.resided_how_long %></p>

      	<% if prospect.number_of_children.present? %>
      		<p class="latolight main-text"><span class="latobold">Number of children: </span><%= prospect.number_of_children %></p>
      		<p class="latolight main-text"><span class="latobold">Ages: </span><%= prospect.ages %></p>
      	<% end %>

      	<% if prospect.co_own_property.present? || prospect.co_own_business.present? %>
      		<p class="latolight main-text"><span class="latobold">Co-Owns Property: </span><%= prospect.co_own_property %></p>
      		<p class="latolight main-text"><span class="latobold">Co-Owns Business: </span><%= prospect.co_own_business %></p>
      	<% end %>





      </div>
      <!--<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-navy">Save changes</button>
      </div>-->
    </div>
  </div>
</div>
				<% end %>

			</table>
			<%= paginate @prospects, :theme => 'twitter-bootstrap-3' %>
		</div>
	</div>
</div>
</div>
</div>

app/views/dashboard/_dashboardQuestions.html.erb
<div class="container-fluid">
	<div class="dashboard-box-top">
	<div class="row">
		<div class="col-md-12">
			<h2 class="main-heading latolight">FAQ Questions<a href="/dashboard/questions/new"><span class="btn btn-navy pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></span></a></h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-hover">
					<tr>
						<th class="latobold main-text">Question</th>
						<th class="latobold main-text">Status</th>
						<th></th>
					</tr>
					<% for question in @questions %>
					<tr>
						<td class="latoregular"><%= link_to question.name, edit_question_path(question) %></td>
						<% if question.status === "published" %>
							<td class="latobold sky-blue"><%= question.status.capitalize %></td>
							<% elsif question.status === "draft" %>
							<td class="latoregular gray"><%= question.status.capitalize %></td>
							<% end %>
						<td>
							<%= link_to question, method: :delete, data: { confirm: "Are you sure?" } do %>
								<span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"	></span>
							<% end %>
						</td>
					</tr>
					<% end %>
				</table>
				<%= paginate @questions, :theme => 'twitter-bootstrap-3' %>
			</div>
		</div>
	</div>
</div>
</div>

app/views/dashboard/_sidebarNav.html.erb
<div class="user-box">
	<p class="latolight small-text"><span class="gray">Hello,</span> <span class="white"><%= current_user.name %></span></p>
</div>
<ul>
	<!--<li><a href="/dashboard">Dashboard</a></li>
	<li><a href="/dashboard/posts">Posts</a></li>
	<li><a href="/dashboard/questions">FAQ</a></li>
	<li><a href="/dashboard/prospects">Prospects</a></li>-->

	<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'index' %>"><a href="/dashboard">Dashboard</a></li>
	<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'posts' %>"><a href="/dashboard/posts">Posts</a></li>
	<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'questions' %>"><a href="/dashboard/questions">FAQ</a></li>
	<li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'prospects' %>"><a href="/dashboard/prospects">Prospects</a></li>


</ul>

app/views/dashboard/editpost.html.erb
<%= render 'dashboardNav' %>

<div class="dashboard-main">
	<div class="sidebar">
		<%= render 'sidebarNav' %>
	</div>
	<div class="main">
		<%= render 'dashboardEditPost' %>
	</div>
</div>

app/views/dashboard/index.html.erb
<%= render 'dashboardNav' %>

<div class="dashboard-main">
	<div class="sidebar">
		<%= render 'sidebarNav' %>
	</div>
	<div class="main">
		<%= render 'dashboardMain' %>
	</div>
</div>

app/views/dashboard/newpost.html.erb
<%= render 'dashboardNav' %>

<div class="dashboard-main">
	<div class="sidebar">
		<%= render 'sidebarNav' %>
	</div>
	<div class="main">
		<%= render 'dashboardNewPost' %>
	</div>
</div>

app/views/dashboard/newquestion.html.erb
<%= render 'dashboardNav' %>

<div class="dashboard-main">
	<div class="sidebar">
		<%= render 'sidebarNav' %>
	</div>
	<div class="main">
		<%= render 'dashboardNewQuestion' %>
	</div>
</div>

app/views/dashboard/posts.html.erb
<%= render 'dashboardNav' %>

<div class="dashboard-main">
	<div class="sidebar">
		<%= render 'sidebarNav' %>
	</div>
	<div class="main">
		<%= render 'dashboardPosts' %>
	</div>
</div>