config/routes.rb
Rails.application.routes.draw do

  resources :prospects

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users

  devise_scope :user do
    get "/admin/sign-in" => 'devise/sessions#new'
    get "/admin/sign-up" => 'devise/registrations#new'
  end
  
  get 'about', to: 'pages#about'
  get 'faq', to: 'pages#faq'
  get 'bio', to: 'pages#bio'
  get 'basic-divorce', to: 'pages#basic'
  get 'divorce-with-property', to: 'pages#property'
  get 'divorce-with-children', to: 'pages#children'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/questions'
  get 'dashboard/prospects'
  get 'dashboard/posts'
  get 'dashboard/posts/new', to: 'dashboard#newpost'
  get 'dashboard/posts/:id/edit', to: 'dashboard#editpost', as: "edit_post"
  get 'dashboard/questions/new', to: 'dashboard#newquestion'
  get 'dashboard/questions/:id/edit', to: 'dashboard#editquestion', as: "edit_question"
  get 'pages/download_pdf'
  get 'pages/download_parenting_class_pdf'
  get 'pages/download_intermediary_pdf'

  get 'posts/tags/:tag', to: 'posts#index', as: "tag"

  resources :questions
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end
  resources :contacts

  root to: 'pages#home'

end

app/views/partials/_disclaimer.html.erb
<p class="latoregular small-text-nospace"><span class="latoblack">Limit of properties</span>&mdash;max of one property. Each additional property is $200.</p>
<p class="latoregular small-text-nospace"><span class="latoblack">Limit of businesses</span>&mdash;max of one business. Each additional business is $200. Does not include valuation of the business.
<p class="latoregular small-text-nospace"><span class="latoblack">Limit of representation</span>&mdash;5 hours billable time. If 5 hours are exceeded the client will be billed $200 per hour. Connie Chadwick is licensed to practice law in the State of Tennessee.</p>
<p class="latoregular small-text-nospace" id="defendant"><span class="latoblack">Defendant</span>&mdash;We do not represent the Defendant and will not give legal advice to the Defendant; however, the Defendant may choose to review and execute the proposed divorce settlement voluntarily. Parties that we do not represent are always encouraged to seek independent counsel before signing any documents.</p>

app/views/partials/_footer.html.erb
<div class="footer-top">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-2">
        <h3 class="latolight ft-hdr light-yellow">Pages</h3>
        <p class="latolight pages-ft"><%= link_to "About", about_path, class: "footer-link" %></p>
        <p class="latolight pages-ft"><%= link_to "Bio", bio_path, class: "footer-link" %></p>
        <p class="latolight pages-ft"><%= link_to "FAQ", faq_path, class: "footer-link" %></p>
        <p class="latolight pages-ft"><%= link_to "Blog", posts_path, class: "footer-link" %></p>
      </div>
      <div class="col-md-5 col-sm-5">
        <h3 class="latolight ft-hdr light-yellow">Recent Posts</h3>
        <% for post in @footer_posts %>
        <p class="latolight recent-ft"><%= link_to post.title, post, class: 'footer-link' %></p>
        <% end %>
      </div>
      <div class="col-md-4 col-sm-5">  
        <h3 class="latolight ft-hdr light-yellow">Follow</h3>
        <div class="row">
          <div class="col-md-3 col-sm-3 col-xs-3">
            <%= link_to image_tag("facebook_g.png", width: "50", class: "follow-img-g"), "https://www.facebook.com/ConnieChadwickLaw", target: "_blank" %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3">
            <%= link_to image_tag("linkedin_g.png", width: "50", class: "follow-img-g"), "https://www.linkedin.com/pub/connie-chadwick/78/194/543", target: "_blank" %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3">
            <%= link_to image_tag("twitter_g.png", width: "50", class: "follow-img-g"), "https://twitter.com/AttyGirl2014", target: "_blank" %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3">
            <%= link_to image_tag("google_plus_g.png", width: "50", class: "follow-img-g"), "https://plus.google.com/u/0/112227991239529852628/posts", target: "_blank" %>
          </div>
        </div>
        
        
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="copyright-text">
          <p class="white latolight text-center">&copy; Copyright 2015 Connie Chadwick Law. All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar-container">
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand latoblack" href="/">Chadwick & Tignor, P.C.</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">


      </ul>

      <ul class="nav navbar-nav navbar-right">


        <li class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'about' %>"><a href="/about">About</a></li>
        <li class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'bio' %>"><a href="/bio">Bio</a></li>
        <li class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'faq' %>"><a href="/faq">FAQ</a></li>
        <li class="<%= 'active' if params[:controller] == 'posts' && params[:action] == 'index' || params[:action] == 'show' %>"><a href="/posts">Blog</a></li>
        <li>
          <%= link_to "tel:6155502800" do %>
            <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> (615) 379-7900
          <% end %>
        </li>
        <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/partials/_panels.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% for question in @question_open %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-<%= question.id %>">
      <h3 class="latobold question-main"><a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= question.id %>" aria-expanded="true" aria-controls="collapse-<%= question.id %>"><%= question.name %></a></h3>
    </div>
    <div id="collapse-<%= question.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading->%= question.id %>">
      <div class="panel-body">
        <p class="latolight question-text"><%= sanitize question.answer %></p>
      </div>
    </div>
  </div>
  <% end %>
  <% for question in @questions_closed %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-<%= question.id %>">
      <h3 class="latobold question-main"><a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= question.id %>" aria-expanded="true" aria-controls="collapse-<%= question.id %>"><%= question.name %></a></h3>
    </div>
    <div id="collapse-<%= question.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading->%= question.id %>">
      <div class="panel-body">
        <p class="latolight question-text"><%= sanitize question.answer %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>