config/routes.rb
Rails.application.routes.draw do

  resources :prospects

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users

  devise_scope :user do
    get "/admin/sign-in" => 'devise/sessions#new'
    get "/admin/sign-up" => 'devise/registrations#new'
  end
  
  get 'about', to: 'pages#about'
  get 'faq', to: 'pages#faq'
  get 'bio', to: 'pages#bio'
  get 'basic-divorce', to: 'pages#basic'
  get 'divorce-with-property', to: 'pages#property'
  get 'divorce-with-children', to: 'pages#children'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/questions'
  get 'dashboard/prospects'
  get 'dashboard/posts'
  get 'dashboard/posts/new', to: 'dashboard#newpost'
  get 'dashboard/posts/:id/edit', to: 'dashboard#editpost', as: "edit_post"
  get 'dashboard/questions/new', to: 'dashboard#newquestion'
  get 'dashboard/questions/:id/edit', to: 'dashboard#editquestion', as: "edit_question"
  get 'pages/download_pdf'
  get 'pages/download_parenting_class_pdf'
  get 'pages/download_intermediary_pdf'

  get 'posts/tags/:tag', to: 'posts#index', as: "tag"

  resources :questions
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end
  resources :contacts

  root to: 'pages#home'

end

app/views/pages/_helplinks.html.erb
<p class="latoregular"><%= link_to "Child Support Guidelines - FAQ", "http://www.tn.gov/humanservices/article/child-support-frequently-asked-questions", target: "_blank" %></p>
<p class="latoregular"><%= link_to "Applying for Child Support Services", "http://www.tn.gov/humanservices/article/child-support-applying-for-services", target: "_blank" %></p>
<p class="latoregular"><%= link_to "Course for Parents", "http://courseforparents.com/states/TN", target: "_blank" %></p>
<p class="latoregular"><%= link_to "Parenting Skills Institute", "http://www.parentingskillsinstitute.com/", target: "_blank" %></p>
<p class="latoregular"><%= link_to "Emily Hastings Counseling and Condflict Resolution", "http://emilyhastings.net", target: "_blank" %></p>

app/views/pages/_steps.html.erb
<h1 class="latoblack">Next Steps:</h1>

<h2 class="latoregular pale-green next-steps">Complete Divorce Packet & Initial Consult</h2>
<p class="latolight main-text">Clients must 
<%= link_to pages_download_pdf_url do %> 
	download
<% end %>
and complete the divorce packet and bring it along with payment in full to the consultation appointment.  Both parties will attend. No additional parties or children will be permitted. Clients should have an agreed settlement in mind, but they are free to ask for advice on how to handle certain situations. We act as a 
<%= link_to pages_download_intermediary_pdf_url do %>
  intermediary
<% end %>

in reaching a full settlement.</p>

<p class="latobold">* If settlement cannot be achieved, BOTH parties will be required to obtain new counsel.</p>

<h2 class="latoregular pale-green next-steps">Draft Production and Review</h2>
<p class="latolight main-text">Clients will recieve a draft of their paperwork within 7 days. Both parties will review the documents and send over ONE round of edits. FINAL copy will be produced and delivered within 7 days.</p>

<h2 class="latoregular pale-green next-steps">Signing of Final Papers and Filing</h2>
<p class="latolight main-text">Both clients will come in to sign the paperwork for filing and pay the applicable filing fees. The Petition, Marital Dissolution Agreement and Summons are filed first. IF the parties have children, the permanent parenting plan, child support worksheet, and wage assignment (if needed) will also be filed.</p>

<p class="latobold">* For clients wanting child support to be paid through the state, please visit <%= link_to "TN Department of Human Services - Child Support: Applying for Services", "http://tn.gov/humanservices/article/child-support-applying-for-services" %>.</p>


<h2 class="latoregular pale-green next-steps">Set Final Hearing</h2>
<p class="latolight main-text">Once the defending party signs the Summons, we will file an Order to set final hearing. (60 days no children; 90 days with children). For divorces including children, both clients must complete a 4-hour certified parenting course and file the completion certificate with our office.</p>

<p class="latobold">
	<%= link_to pages_download_parenting_class_pdf_url do %>
		Parenting Class Information PDF
	<% end %>
</p>

<h2 class="latoregular pale-green next-steps">Final Hearing</h2>
<p class="latolight main-text">Petitioning party must attend final hearing to finalize the divorce. This process consists of an appearance before a local judge to answer a few questions and will take only a few minutes. The defending party does not have to attend, but can if they so choose. </p>

app/views/pages/basic.html.erb
<% content_for :title, "Basic Divorce" %>
<%= render 'partials/navbar' %>
<div class="page-container">
	<div class="container">
		
		<div class="row">
			<div class="col-md-8">
				<h2 class="latoblack question-hdr">Basic Divorce</h2>
				<p class="latolight main-text">You have taken the first step of filling out the initial information needed to do a conflict check to ensure that we can continue. Once we confirm that there are no conflicts, we will contact you and schedule the initial consult. Download the divorce packet and print. This information packet must be filled out completely and brought to your initial consult. If there are any questions about the forms you can email us at <%= mail_to "vcolvin@sbdlaw.net" %>.</p>
				<div class="pdf-doc">
					<p class="latolight main-text">
					<%= link_to pages_download_pdf_url do %>
						<%= image_tag "pdf.png", height: "40", style: "margin-right:10px;" %> Divorce Packet PDF</p>
					<% end %>
				</p>
				</div>
				<div class="steps">
					<%= render 'steps' %>
				</div>
			</div>
			<div class="col-md-offset-1 col-md-3">
				<h2 class="latoblack helpful-links">Helpful Links</h2>
				<%= render 'helplinks' %>
 			</div>
		</div>
	</div>
</div>
<%= render 'partials/footer' %>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67516802-1', 'auto');
    ga('send', 'pageview');

</script>

app/views/pages/bio.html.erb
<% content_for :title, "About Connie" %>
<% content_for :content, "Connie Chadwick is an attorney in Franklin, TN, practicing family law, personal injury, and civil litigations." %>
<%= render 'partials/navbar' %>
<div class="bio-container">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="latoblack about-hdr">A little bit about Connie...</h2>
				<%= image_tag "connie2_alt3.jpg", class: "about-img" %>

				<p class="latolight about-text"><span class="latoblack">Connie Chadwick</span> focuses her law practice on civil litigation, personal injury, and family law.  Connie earned her Doctorate of Jurisprudence from The Nashville School of Law after earning her Bachelor of Science in Accounting from Lipscomb University.  Connie is a seasoned business professional who has transitioned to the legal profession with an intense drive to achieve and deliver results for her clients. As the first female associate at Schell & Davies, LLC, Connie adds a unique perspective and set of experiences to an extremely well known and successful domestic litigation firm.</p>
				<p class="latolight about-text">Connie has strong management expertise and ability to oversee diverse objectives and challenging deadlines with a sense of confidence and commitment. With more than 15 years of experience in small business and entrepreneurial organizations within the banking, construction and real estate industries, Connie brings a diverse skill set to the table.  She is extremely detailed-oriented with excellent research, investigative, and communication skills. Connie demonstrates independent judgment and decision-making abilities with the highest level of confidentiality and ethics.</p>
				<p class="latolight about-text">On a more personal note, Connie is a single parent of four children whose ages range from 9 years to 17 years old. Connie knows from experience how painful and traumatic divorce can be to the couple and family. Divorce is not only the most significant  set back financially, but divorce can derail the family traditions and customs.  Children must be handled with care.  The parenting plan that sets out all the co-parenting rules from the beginning is of utmost importance.  Connie guides her clients through the divorce process with empathy in tact for all those involved. A great attorney not only offers legal advice, but real life advice that works for you. Connie is the best at combining both of those attributes.</p>
				<p class="latobold about-text"><a href="http://mydigitalpublication.com/publication/?i=290439">"Avoid the "Parent Traps" of Divorce"</a> by Connie Chadwick from The NALS Docket</p>
			</div>

		</div>
	</div>
</div>
<div class="message-container">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="latolight about-msg">Send me a message...</h2>
				<div class="row">
					<%= form_for Contact.new do |f| %>
					<%= invisible_captcha %>
					<div class="col-md-6">
						<div class="form-group">
							<%= f.text_field :name, class: "form-control-msg", placeholder: "Full Name" %>
						</div>
						<div class="form-group">
							<%= f.text_field :email, class: "form-control-msg", placeholder: "Email" %>
						</div>
						<div class="form-group">
							<%= f.text_field :phone, class: "form-control-msg", placeholder: "Phone" %>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<%= f.text_area :message, class: "form-control-msg", placeholder: "Add a message", rows: "6", required: "required" %>
						</div>
					</div>
					<div class="col-md-12">
						<%= f.submit "Send Message", class: "btn btn-bright", name: "bio" %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render 'partials/footer' %>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67516802-1', 'auto');
    ga('send', 'pageview');

</script>

app/views/pages/children.html.erb
<% content_for :title, "Divorce with Children" %>
<%= render 'partials/navbar' %>
<div class="page-container">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h2 class="latoblack question-hdr">Divorce with Children</h2>
				<p class="latolight main-text">You have taken the first step of filling out the initial information needed to do a conflict check to ensure that we can continue. Once we confirm that there are no conflicts, we will contact you and schedule the initial consult. Download the divorce packet and print. This information packet must be filled out completely and brought to your initial consult. If there are any questions about the forms you can email us at <%= mail_to "vcolvin@sbdlaw.net" %>. </p>
				<div class="pdf-doc">
					<p class="latolight main-text">
					<%= link_to pages_download_pdf_url do %>
						<%= image_tag "pdf.png", height: "40", style: "margin-right:10px;" %> Divorce Packet PDF</p>
					<% end %>
				</p>
				</div>
				<div class="steps">
					<%= render 'steps' %>
				</div>
			</div>
			<div class="col-md-offset-1 col-md-3">
				<h2 class="latoblack helpful-links">Helpful Links</h2>
				<%= render 'helplinks' %>
			</div>
		</div>
	</div>
</div>
<%= render 'partials/footer' %>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67516802-1', 'auto');
    ga('send', 'pageview');

</script>

app/views/pages/faq.html.erb
<% content_for :title, "Frequently Asked Questions" %>
<% content_for :content, "Frequenly asked questions about divorce." %>
<%= render 'partials/navbar' %>

<div class="page-container">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h2 class="latoblack question-hdr navy">Got questions?</h2>
				<p class="latolight gray">* Click on the question to view the answer.</p>
				

				<%= render 'partials/panels' %>
			</div>
			<div class="col-md-offset-1 col-md-3">
				<h3 class="latobold faq-question navy">Have another question?</h3>
				<p class="latoregular gray">If your question is not answered by our FAQ, contact us using the form below.</p>
				<div class="faq-form">
					<%= form_for Contact.new do |f| %>
					<%= invisible_captcha %>
						<div class="form-group">
							<label class="sr-only">Name</label>
							<%= f.text_field :name, class: "form-control", placeholder: "Full Name" %>
						</div>
						<div class="form-group">
							<label class="sr-only">Name</label>
							<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
						</div>
						<div class="form-group">
							<label class="sr-only">Name</label>
							<%= f.text_field :phone, class: "form-control", placeholder: "Phone" %>
						</div>
						<div class="form-group">
							<label class="sr-only">Name</label>
							<%= f.text_area :message, class: "form-control", placeholder: "What is your question?", rows: "5" %>
						</div>
						<%= f.submit "Submit Question", class: "btn btn-bright", name: "ask" %>
					<% end %>
				</div>
			</div>	
		</div>
	</div>
</div>

<%= render 'partials/footer' %>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67516802-1', 'auto');
    ga('send', 'pageview');

</script>

app/views/pages/property.html.erb
<% content_for :title, "Divorce with Property" %>
<%= render 'partials/navbar' %>
<div class="page-container">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h2 class="latoblack question-hdr">Divorce with Property</h2>
				<p class="latolight main-text">You have taken the first step of filling out the initial information needed to do a conflict check to ensure that we can continue. Once we confirm that there are no conflicts, we will contact you and schedule the initial consult. Download the divorce packet and print. This information packet must be filled out completely and brought to your initial consult. If there are any questions about the forms you can email us at <%= mail_to "vcolvin@sbdlaw.net" %>. </p>
				<div class="pdf-doc">
					<p class="latolight main-text">
					<%= link_to pages_download_pdf_url do %>
						<%= image_tag "pdf.png", height: "40", style: "margin-right:10px;" %> Divorce Packet PDF</p>
					<% end %>
				</p>
				</div>
				<div class="steps">
					<%= render 'steps' %>
				</div>
			</div>
			<div class="col-md-offset-1 col-md-3">
				<h2 class="latoblack helpful-links">Helpful Links</h2>
				<%= render 'helplinks' %>
			</div>
		</div>
	</div>
</div>
<%= render 'partials/footer' %>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67516802-1', 'auto');
    ga('send', 'pageview');

</script>